#!/bin/bash          
echo "args: $@"
echo "demo param: $VELOCITY_PARAM_demo"
echo "boolean1 param: $VELOCITY_PARAM_boolean1"
echo "boolean2 param: $VELOCITY_PARAM_boolean2"
echo "boolean3 param: $VELOCITY_PARAM_boolean3"
echo "masked1 param: $VELOCITY_PARAM_masked1"
echo "integer1 param: $VELOCITY_PARAM_integer1"
echo "double1 param: $VELOCITY_PARAM_double1"
echo "recipients param: $VELOCITY_PARAM_recipients"